services:
  nginx:
    image: linxue/nginx:v1
    ports:
      - "80:80"
    networks:
      - custom-bridge
    depends_on:
      - app

  redis:
    image: redis:alpine
    command: redis-server --requirepass mypassword
    ports:
      - "6379:6379"
    networks:
      - custom-bridge
    volumes:
    - $PWD/redis-data:/var/lib/redis
    - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  app:
    image: linxue/homework-docker:v1
    networks:
      - custom-bridge
    depends_on:
      - redis
    expose:
      - "8080"
    deploy:
      replicas: 2

networks:
  custom-bridge:
    driver: bridge